package io.jpress.model;

import io.jpress.model.base.BaseGroup;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="groupinfo",primaryKey="id")
public class Groupinfo extends BaseGroup<Groupinfo> {
	private static final long serialVersionUID = 1L;

}
