package io.jpress.model;

import io.jpress.model.base.BaseMessage;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="message",primaryKey="id")
public class Message extends BaseMessage<Message> {
	private static final long serialVersionUID = 1L;

}
