package io.jpress.model;

import io.jpress.model.base.BasePrize;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="prize",primaryKey="id")
public class Prize extends BasePrize<Prize> {
	private static final long serialVersionUID = 1L;

}
