package io.jpress.model;

import io.jpress.model.base.BaseSignup;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="signup",primaryKey="id")
public class Signup extends BaseSignup<Signup> {
	private static final long serialVersionUID = 1L;

}
